### ISSUE TITLE
QEP 1: Implicitly-Scoped Qubit Allocation

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-compiler#795]
This issue tracks the implementation of [QEP 1: Implicitly-Scoped Qubit Allocation](https://github.com/microsoft/qsharp-language/blob/main/Approved/1-implicitly-scoped-qubit-allocation.md). The feature branch is [feature/inline-qubit-scope](https://github.com/microsoft/qsharp-compiler/tree/feature/inline-qubit-scope).

- [x] Deprecate `using` and `borrowing` keywords and replace with `use` and `borrow` (#804)
- [x] Allow `use` and `borrow` statements to be followed by either a block `{ ... }` or a semicolon `;` (#803)
- [x] Deprecate parentheses around block statement headers (#791)

**Comment by cgranade** [comment]
Thinking about `using` → `use` and `borrowing` → `borrow` a bit more, it feels a bit awkward to use [present participles](https://www.merriam-webster.com/dictionary/present%20participle) to represent an action taken by an operation, given that we elsewhere use finite verb phrases to directly indicate the tense and subject of that verb. Concretely, the gerund "using" on its own doesn't have a tense to make it clear _when_ something is used. Moving to "use" makes that tense explicit, which strikes me as a very good thing for readability.

**Comment by tcNickolas** [comment]
When this change becomes breaking, will we offer the users a tool to mass-migrate to the new syntax automatically, like we did in the past (I think it was around 0.3 version)? I've seen a mention of a code action in the proposal, but migrating a sizeable code base would require a lot of effort without such tool.

**Comment by samarsha** [comment]
We've been discussing using [QsFmt](https://github.com/samarsha/qsfmt) to automatically update deprecated syntax across an entire project. It needs some more work to be able to do that, though.
