### ISSUE TITLE
QEP 2: Enhanced Array Literals

### ISSUE THREAD

**Issue by samarsha** [microsoft/qsharp-compiler#857]
This issue tracks the implementation of [QEP 2: Enhanced Array Literals](https://github.com/microsoft/qsharp-language/blob/main/Approved/2-enhanced-array-literals.md). The feature branch is [feature/qep2](https://github.com/microsoft/qsharp-compiler/tree/feature/qep2).

- [x] Support the empty array constructor, `[]` (#884)
  - [x] Add Hindley-Milner type inference module (#917)
  - [x] Replace existing type inference with Hindley-Milner (#940)
  - [x] Update usages of obsolete range fields in `QsTypeParameter` and `UserDefinedType` (#952)
- [x] Support the repeated constant array constructor, `[x, size = n]` (#856)
  - [x] Support `[x, size = n]` in attribute arguments (#884)
- [x] Add `SizedArray` to NamespaceManager.fs (`ExpressionHash`) and QsharpCodeOutput.cs (#963)
- [x] Update optimizations for `SizedArray`: ConstantPropagation.fs, Evaluation.fs, HelperFunctions.fs (`isLiteral`) (#963)
- [x] Address issues from bug bash (#980)
- [ ] Update QIR generation for `SizedArray` expression kind

Deferred:

* Deprecate the `new Type[n]` array constructor (#956)
